### ISSUE TITLE
Unable to deploy with what looks like standard config

### ISSUE THREAD

**Issue by huntson** [Uninett/nav-container#25]
I have put the following in a file and then run docker-compose up -d.  It pulls everything and the gives me the following error:

`unable to prepare context: path "/root/carbon-cache" not found`

This is the compose file:

```yml
version: '3.5'
services:
  nav:
    build:
      context: .
      args:
        NAV_VERSION: 5.6.0
    ports:
      - "80:80"
      - "162:162/udp"
    volumes:
      - logs:/var/log/nav:Z
      - roomimages:/var/lib/nav/uploads/images/rooms:Z
    depends_on:
      - postgres
      - carbon-cache
      - graphite-web
    environment:
      - PGHOST=postgres
      - PGDATABASE=nav
      - PGUSER=nav
      - PGPASSWORD=s3cret
      - PGPORT=5432
      - CARBONHOST=carbon-cache
      - CARBONPORT=2003
      - GRAPHITEWEB=http://graphite-web/
      - NOINITDB=0
#    env_file:
#      - nav-variables.env
    restart: always

  postgres:
    image: "docker.io/postgres:12"
    volumes:
      - postgres:/var/lib/postgresql/data:Z
    # The following vars are documented at https://hub.docker.com/_/postgres
    environment:
      - POSTGRES_PASSWORD=s3cret
      - POSTGRES_USER=nav
      - POSTGRES_DB=nav
    restart: always

  carbon-cache:
    build: ./carbon-cache
    volumes:
      - whisper:/var/lib/graphite/whisper:z
    restart: always

  graphite-web:
    build: ./graphite-web
     We don't really want this to be public, since there is no authentication
     ports:"4399:80"
    environment:
      - TIME_ZONE=America/New_York
      - CARBONLINK_HOSTS=carbon-cache:7002
    volumes:
      - whisper:/var/lib/graphite/storage/whisper:z
    restart: always

volumes:
  whisper:
    driver: local
  postgres:
    driver: local
  logs:
    driver: local
  roomimages:
    driver: local
```
